name: Deploy + Test API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy ke Server
        run: |
          cd /home/ubuntu/app
          git pull origin master
          docker compose up -d --build

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Check File
        run: |
          ls -la tests

      - name: Run Postman Collection
        run: |
          newman run tests/collection.json
