name: Deploy + Test API

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Info
        run: |
          echo "User:"
          whoami
          echo "Directory:"
          pwd
          echo "Files:"
          ls -la

      - name: Deploy ke Server
        run: |
          cd /home/ubuntu/app || exit 1
          git pull origin master || exit 1
          docker compose up -d --build || exit 1

      - name: Install Node.js & Newman
        run: |
          sudo apt update
          sudo apt install -y nodejs npm
          npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run tests/collection.json
