name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo "USER:"
          whoami
          echo "PWD:"
          pwd
          echo "FILES:"
          ls -la

      - name: Deploy
        run: |
          echo "Masuk folder app"
          cd /home/ubuntu/app || exit 1

          echo "Git pull"
          git pull origin master || exit 1

          echo "Docker run"
          docker compose up -d --build || exit 1
